services:
  sgeapp:
    container_name: SegApp
    build:
      context: .
      args:
        - DEV=true
    ports:
      - 8000:8000
    volumes:
      - ./sgeapp:/sgeapp
      - ./data/web/static:/data/web/static/
      - ./data/web/media:/data/web/media/
      - ./dotenv_files/.env:/sgeapp/.env
    env_file:
      - ./dotenv_files/.env
    depends_on:
      - psql
  psql:
    container_name: psql
    image: postgres:13-alpine
    volumes:
      - ./data/postgres/data:/var/lib/postgresql/data
    env_file:
      - ./dotenv_files/.env
