services:
  sgeapp:
    container_name: sgeapp
    build:
      context: .
      args:
        - DEV=true
    ports:
      - 8000:8000
    volumes:
      - ./sgeapp:/sgeapp
      - ./data/web/static:/data/web/static/
      - ./data/web/media:/data/web/media/
      - - .env:/sgeapp/.env 
    env_file:
     environment:
      - DB_NAME=${DB_NAME}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - SECRET_KEY=${SECRET_KEY}
      - DEBUG=${DEBUG}
    depends_on:
      - psql
  psql:
    container_name: psql
    image: postgres:13-alpine
    volumes:
      - ./data/postgres/data:/var/lib/postgresql/data
    env_file:
      - ./dotenv_files/.env