---
name: Checks

on: [push]

jobs: 
  test-lint:
    name: Test and Lint
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Criar arquivo .env temporário
        run: |
          mkdir -p dotenv_files
          cat <<EOF > dotenv_files/.env
          DATABASE_URL=postgres://user:password@psql/db
          API_KEY=${{ secrets.API_KEY }}
          SECRET_KEY=${{ secrets.SECRET_KEY }}
          DEBUG=True
          EOF

      - name: Subir serviços com Docker Compose
        run: docker compose up -d

      - name: Run Tests
        run: docker compose run --rm sgeapp sh -c "
          python /sgeapp/manage.py wait_for_db &&
          python /sgeapp/manage.py test"
      - name: Run Lint
        run: docker compose run --rm sgeapp sh -c "flake8"

      - name: Derrubar serviços
        if: always()
        run: docker compose down
