---
  name: Checks
  
  on: [push]
  
  jobs:
    test-lint:
      name: Test and Lint
      runs-on: ubuntu-20.04
      steps:
        - uses: actions/checkout@v4.2.2
        
        - name: Login to Docker Hub
          uses: docker/login-action@v3.3.0
          with:
            username: ${{ secrets.DOCKERHUB_USER }}
            password: ${{ secrets.DOCKERHUB_TOKEN }}
             # Configura as variáveis de ambiente
        
        - name: Set Environment Variables
          run: |
            echo "DB_NAME=${{ secrets.DB_NAME }}" >> .env
            echo "DB_USER=${{ secrets.DB_USER }}" >> .env
            echo "DB_PASSWORD=${{ secrets.DB_PASSWORD }}" >> .env
            echo "SECRET_KEY=${{ secrets.SECRET_KEY }}" >> .env
            echo "DEBUG=${{ secrets.DEBUG }}" >> .env
            
        - name: Checkout
          uses: actions/checkout@v2
        - name: Test
          run: docker compose run --rm sgeapp sh -c "python manage.py wait_for_db && python manage.py test"
        - name: Lint
          run: docker compose run --rm sgeapp sh -c "flake8"
